export const LOOKUP_FIELDS = {
  dealAccount: "deals.account_name",
  dealContact: "deals.contact_name",
  dealOwner: "deals.owner_name",
  dealCountry: "deals.country",
  dealRegion: "deals.region",
  dealRegionPrefix: "deals.region",
  dealProduct: "deals.product",
  dealStage: "deals.stage",
  dealStatus: "deals.status",
  dealCustomerBudget: "deals.customer_budget",
  dealSource: "deals.source",
  dealLastTouch: "deals.last_touch",
  customerCompany: "customers.company_name",
  customerOwner: "customers.account_owner",
  customerRegion: "customers.region",
  customerSegment: "customers.segment",
  customerMrr: "customers.mrr",
  customerStatus: "customers.status",
  customerLastTouch: "customers.last_touch",
  catalogSku: "catalog.sku",
  catalogProduct: "catalog.product_name",
  catalogCategory: "catalog.category",
  catalogTier: "catalog.partner_tier",
  catalogPrice: "catalog.list_price",
  catalogMargin: "catalog.margin",
  catalogAvailability: "catalog.availability",
  documentType: "documents.doc_type",
  userRole: "users.role",
  teamRole: "team.portal_role",
  teamStatus: "team.status",
  auditSeverity: "audit.severity",
  partnerStatus: "partners.status",
  partnerCountry: "partners.onboarding.country",
  partnerRegionPrefix: "partners.onboarding.region",
  partnerBusinessType: "partners.onboarding.business_type",
  partnerAnnualTurnover: "partners.onboarding.annual_turnover",
  partnerEmployeeCount: "partners.onboarding.employee_count",
} as const;

export type LookupFieldName = (typeof LOOKUP_FIELDS)[keyof typeof LOOKUP_FIELDS];
