// Governed reference data: every ISO 3166-1 country/territory, grouped into
// LIVEY Sales Regions, with its primary ISO 4217 currency.
//
// The blueprint (product.md Section 5.1 / 23.3) requires "Country records
// use stable country codes from the governed dataset" and "A Sales Region
// contains one or more countries; a country belongs to one primary active
// Sales Region at a time" but does not enumerate a canonical region list —
// Sales Region membership is explicitly Super Admin-governed. The seven
// regions below are a reasonable global partition, not a blueprint mandate;
// they can be re-governed (with effective-dated country membership changes,
// per the same section) without code changes to anything that consumes
// this file, since everything downstream keys off `regionKey` + `code`.
//
// Currency is each country's present-day ISO 4217 currency for reference/
// display purposes only. It is NOT the authoritative money model — per the
// blueprint, USD alone is authoritative for commercial calculations and
// local currency is a separately labelled, timestamped reference snapshot.
// See src/domain/contracts/taxonomy.ts's CURRENCY_CODES (USD/INR), which
// this file does not change.

export const SALES_REGIONS = [
  { key: "north_america", name: "North America" },
  { key: "latin_america", name: "Latin America & Caribbean" },
  { key: "europe", name: "Europe" },
  { key: "middle_east_africa", name: "Middle East & Africa" },
  { key: "india", name: "India" },
  { key: "greater_china", name: "Greater China" },
  { key: "apac", name: "Asia Pacific" },
] as const;

export type SalesRegionKey = (typeof SALES_REGIONS)[number]["key"];

export type WorldCountry = {
  /** ISO 3166-1 alpha-2 code */
  code: string;
  name: string;
  regionKey: SalesRegionKey;
  /** ISO 4217 currency code (present-day reference default) */
  currencyCode: string;
};

export const WORLD_COUNTRIES: readonly WorldCountry[] = [
  // --- North America ---
  { code: "US", name: "United States", regionKey: "north_america", currencyCode: "USD" },
  { code: "CA", name: "Canada", regionKey: "north_america", currencyCode: "CAD" },
  { code: "BM", name: "Bermuda", regionKey: "north_america", currencyCode: "BMD" },
  { code: "GL", name: "Greenland", regionKey: "north_america", currencyCode: "DKK" },
  {
    code: "PM",
    name: "Saint Pierre and Miquelon",
    regionKey: "north_america",
    currencyCode: "EUR",
  },

  // --- Latin America & Caribbean ---
  { code: "MX", name: "Mexico", regionKey: "latin_america", currencyCode: "MXN" },
  { code: "GT", name: "Guatemala", regionKey: "latin_america", currencyCode: "GTQ" },
  { code: "BZ", name: "Belize", regionKey: "latin_america", currencyCode: "BZD" },
  { code: "SV", name: "El Salvador", regionKey: "latin_america", currencyCode: "USD" },
  { code: "HN", name: "Honduras", regionKey: "latin_america", currencyCode: "HNL" },
  { code: "NI", name: "Nicaragua", regionKey: "latin_america", currencyCode: "NIO" },
  { code: "CR", name: "Costa Rica", regionKey: "latin_america", currencyCode: "CRC" },
  { code: "PA", name: "Panama", regionKey: "latin_america", currencyCode: "PAB" },
  { code: "CU", name: "Cuba", regionKey: "latin_america", currencyCode: "CUP" },
  { code: "JM", name: "Jamaica", regionKey: "latin_america", currencyCode: "JMD" },
  { code: "HT", name: "Haiti", regionKey: "latin_america", currencyCode: "HTG" },
  { code: "DO", name: "Dominican Republic", regionKey: "latin_america", currencyCode: "DOP" },
  { code: "BS", name: "Bahamas", regionKey: "latin_america", currencyCode: "BSD" },
  { code: "BB", name: "Barbados", regionKey: "latin_america", currencyCode: "BBD" },
  { code: "TT", name: "Trinidad and Tobago", regionKey: "latin_america", currencyCode: "TTD" },
  { code: "GD", name: "Grenada", regionKey: "latin_america", currencyCode: "XCD" },
  { code: "LC", name: "Saint Lucia", regionKey: "latin_america", currencyCode: "XCD" },
  {
    code: "VC",
    name: "Saint Vincent and the Grenadines",
    regionKey: "latin_america",
    currencyCode: "XCD",
  },
  { code: "AG", name: "Antigua and Barbuda", regionKey: "latin_america", currencyCode: "XCD" },
  { code: "KN", name: "Saint Kitts and Nevis", regionKey: "latin_america", currencyCode: "XCD" },
  { code: "DM", name: "Dominica", regionKey: "latin_america", currencyCode: "XCD" },
  { code: "PR", name: "Puerto Rico", regionKey: "latin_america", currencyCode: "USD" },
  { code: "VI", name: "U.S. Virgin Islands", regionKey: "latin_america", currencyCode: "USD" },
  { code: "VG", name: "British Virgin Islands", regionKey: "latin_america", currencyCode: "USD" },
  { code: "KY", name: "Cayman Islands", regionKey: "latin_america", currencyCode: "KYD" },
  { code: "TC", name: "Turks and Caicos Islands", regionKey: "latin_america", currencyCode: "USD" },
  { code: "AI", name: "Anguilla", regionKey: "latin_america", currencyCode: "XCD" },
  { code: "MS", name: "Montserrat", regionKey: "latin_america", currencyCode: "XCD" },
  { code: "AW", name: "Aruba", regionKey: "latin_america", currencyCode: "AWG" },
  { code: "CW", name: "Curaçao", regionKey: "latin_america", currencyCode: "ANG" },
  { code: "SX", name: "Sint Maarten", regionKey: "latin_america", currencyCode: "ANG" },
  {
    code: "BQ",
    name: "Bonaire, Sint Eustatius and Saba",
    regionKey: "latin_america",
    currencyCode: "USD",
  },
  { code: "GP", name: "Guadeloupe", regionKey: "latin_america", currencyCode: "EUR" },
  { code: "MQ", name: "Martinique", regionKey: "latin_america", currencyCode: "EUR" },
  { code: "BL", name: "Saint Barthélemy", regionKey: "latin_america", currencyCode: "EUR" },
  { code: "MF", name: "Saint Martin", regionKey: "latin_america", currencyCode: "EUR" },
  { code: "CO", name: "Colombia", regionKey: "latin_america", currencyCode: "COP" },
  { code: "VE", name: "Venezuela", regionKey: "latin_america", currencyCode: "VES" },
  { code: "GY", name: "Guyana", regionKey: "latin_america", currencyCode: "GYD" },
  { code: "SR", name: "Suriname", regionKey: "latin_america", currencyCode: "SRD" },
  { code: "GF", name: "French Guiana", regionKey: "latin_america", currencyCode: "EUR" },
  { code: "EC", name: "Ecuador", regionKey: "latin_america", currencyCode: "USD" },
  { code: "PE", name: "Peru", regionKey: "latin_america", currencyCode: "PEN" },
  { code: "BR", name: "Brazil", regionKey: "latin_america", currencyCode: "BRL" },
  { code: "BO", name: "Bolivia", regionKey: "latin_america", currencyCode: "BOB" },
  { code: "PY", name: "Paraguay", regionKey: "latin_america", currencyCode: "PYG" },
  { code: "CL", name: "Chile", regionKey: "latin_america", currencyCode: "CLP" },
  { code: "AR", name: "Argentina", regionKey: "latin_america", currencyCode: "ARS" },
  { code: "UY", name: "Uruguay", regionKey: "latin_america", currencyCode: "UYU" },
  { code: "FK", name: "Falkland Islands", regionKey: "latin_america", currencyCode: "FKP" },
  {
    code: "GS",
    name: "South Georgia and the South Sandwich Islands",
    regionKey: "latin_america",
    currencyCode: "GBP",
  },

  // --- Europe ---
  { code: "IS", name: "Iceland", regionKey: "europe", currencyCode: "ISK" },
  { code: "NO", name: "Norway", regionKey: "europe", currencyCode: "NOK" },
  { code: "SE", name: "Sweden", regionKey: "europe", currencyCode: "SEK" },
  { code: "FI", name: "Finland", regionKey: "europe", currencyCode: "EUR" },
  { code: "DK", name: "Denmark", regionKey: "europe", currencyCode: "DKK" },
  { code: "FO", name: "Faroe Islands", regionKey: "europe", currencyCode: "DKK" },
  { code: "IE", name: "Ireland", regionKey: "europe", currencyCode: "EUR" },
  { code: "GB", name: "United Kingdom", regionKey: "europe", currencyCode: "GBP" },
  { code: "GG", name: "Guernsey", regionKey: "europe", currencyCode: "GBP" },
  { code: "JE", name: "Jersey", regionKey: "europe", currencyCode: "GBP" },
  { code: "IM", name: "Isle of Man", regionKey: "europe", currencyCode: "GBP" },
  { code: "FR", name: "France", regionKey: "europe", currencyCode: "EUR" },
  { code: "MC", name: "Monaco", regionKey: "europe", currencyCode: "EUR" },
  { code: "BE", name: "Belgium", regionKey: "europe", currencyCode: "EUR" },
  { code: "NL", name: "Netherlands", regionKey: "europe", currencyCode: "EUR" },
  { code: "LU", name: "Luxembourg", regionKey: "europe", currencyCode: "EUR" },
  { code: "DE", name: "Germany", regionKey: "europe", currencyCode: "EUR" },
  { code: "CH", name: "Switzerland", regionKey: "europe", currencyCode: "CHF" },
  { code: "LI", name: "Liechtenstein", regionKey: "europe", currencyCode: "CHF" },
  { code: "AT", name: "Austria", regionKey: "europe", currencyCode: "EUR" },
  { code: "ES", name: "Spain", regionKey: "europe", currencyCode: "EUR" },
  { code: "AD", name: "Andorra", regionKey: "europe", currencyCode: "EUR" },
  { code: "PT", name: "Portugal", regionKey: "europe", currencyCode: "EUR" },
  { code: "IT", name: "Italy", regionKey: "europe", currencyCode: "EUR" },
  { code: "SM", name: "San Marino", regionKey: "europe", currencyCode: "EUR" },
  { code: "VA", name: "Vatican City", regionKey: "europe", currencyCode: "EUR" },
  { code: "MT", name: "Malta", regionKey: "europe", currencyCode: "EUR" },
  { code: "GR", name: "Greece", regionKey: "europe", currencyCode: "EUR" },
  { code: "CY", name: "Cyprus", regionKey: "europe", currencyCode: "EUR" },
  { code: "PL", name: "Poland", regionKey: "europe", currencyCode: "PLN" },
  { code: "CZ", name: "Czechia", regionKey: "europe", currencyCode: "CZK" },
  { code: "SK", name: "Slovakia", regionKey: "europe", currencyCode: "EUR" },
  { code: "HU", name: "Hungary", regionKey: "europe", currencyCode: "HUF" },
  { code: "SI", name: "Slovenia", regionKey: "europe", currencyCode: "EUR" },
  { code: "HR", name: "Croatia", regionKey: "europe", currencyCode: "EUR" },
  { code: "BA", name: "Bosnia and Herzegovina", regionKey: "europe", currencyCode: "BAM" },
  { code: "RS", name: "Serbia", regionKey: "europe", currencyCode: "RSD" },
  { code: "ME", name: "Montenegro", regionKey: "europe", currencyCode: "EUR" },
  { code: "MK", name: "North Macedonia", regionKey: "europe", currencyCode: "MKD" },
  { code: "AL", name: "Albania", regionKey: "europe", currencyCode: "ALL" },
  { code: "XK", name: "Kosovo", regionKey: "europe", currencyCode: "EUR" },
  { code: "RO", name: "Romania", regionKey: "europe", currencyCode: "RON" },
  { code: "BG", name: "Bulgaria", regionKey: "europe", currencyCode: "BGN" },
  { code: "MD", name: "Moldova", regionKey: "europe", currencyCode: "MDL" },
  { code: "UA", name: "Ukraine", regionKey: "europe", currencyCode: "UAH" },
  { code: "BY", name: "Belarus", regionKey: "europe", currencyCode: "BYN" },
  { code: "LT", name: "Lithuania", regionKey: "europe", currencyCode: "EUR" },
  { code: "LV", name: "Latvia", regionKey: "europe", currencyCode: "EUR" },
  { code: "EE", name: "Estonia", regionKey: "europe", currencyCode: "EUR" },
  { code: "RU", name: "Russia", regionKey: "europe", currencyCode: "RUB" },
  { code: "GI", name: "Gibraltar", regionKey: "europe", currencyCode: "GIP" },
  { code: "AX", name: "Åland Islands", regionKey: "europe", currencyCode: "EUR" },
  { code: "SJ", name: "Svalbard and Jan Mayen", regionKey: "europe", currencyCode: "NOK" },

  // --- Middle East & Africa ---
  { code: "TR", name: "Turkey", regionKey: "middle_east_africa", currencyCode: "TRY" },
  { code: "IL", name: "Israel", regionKey: "middle_east_africa", currencyCode: "ILS" },
  { code: "PS", name: "Palestine", regionKey: "middle_east_africa", currencyCode: "ILS" },
  { code: "JO", name: "Jordan", regionKey: "middle_east_africa", currencyCode: "JOD" },
  { code: "LB", name: "Lebanon", regionKey: "middle_east_africa", currencyCode: "LBP" },
  { code: "SY", name: "Syria", regionKey: "middle_east_africa", currencyCode: "SYP" },
  { code: "IQ", name: "Iraq", regionKey: "middle_east_africa", currencyCode: "IQD" },
  { code: "IR", name: "Iran", regionKey: "middle_east_africa", currencyCode: "IRR" },
  { code: "SA", name: "Saudi Arabia", regionKey: "middle_east_africa", currencyCode: "SAR" },
  { code: "YE", name: "Yemen", regionKey: "middle_east_africa", currencyCode: "YER" },
  { code: "OM", name: "Oman", regionKey: "middle_east_africa", currencyCode: "OMR" },
  {
    code: "AE",
    name: "United Arab Emirates",
    regionKey: "middle_east_africa",
    currencyCode: "AED",
  },
  { code: "QA", name: "Qatar", regionKey: "middle_east_africa", currencyCode: "QAR" },
  { code: "BH", name: "Bahrain", regionKey: "middle_east_africa", currencyCode: "BHD" },
  { code: "KW", name: "Kuwait", regionKey: "middle_east_africa", currencyCode: "KWD" },
  { code: "GE", name: "Georgia", regionKey: "middle_east_africa", currencyCode: "GEL" },
  { code: "AM", name: "Armenia", regionKey: "middle_east_africa", currencyCode: "AMD" },
  { code: "AZ", name: "Azerbaijan", regionKey: "middle_east_africa", currencyCode: "AZN" },
  { code: "EG", name: "Egypt", regionKey: "middle_east_africa", currencyCode: "EGP" },
  { code: "LY", name: "Libya", regionKey: "middle_east_africa", currencyCode: "LYD" },
  { code: "TN", name: "Tunisia", regionKey: "middle_east_africa", currencyCode: "TND" },
  { code: "DZ", name: "Algeria", regionKey: "middle_east_africa", currencyCode: "DZD" },
  { code: "MA", name: "Morocco", regionKey: "middle_east_africa", currencyCode: "MAD" },
  { code: "EH", name: "Western Sahara", regionKey: "middle_east_africa", currencyCode: "MAD" },
  { code: "MR", name: "Mauritania", regionKey: "middle_east_africa", currencyCode: "MRU" },
  { code: "ML", name: "Mali", regionKey: "middle_east_africa", currencyCode: "XOF" },
  { code: "NE", name: "Niger", regionKey: "middle_east_africa", currencyCode: "XOF" },
  { code: "TD", name: "Chad", regionKey: "middle_east_africa", currencyCode: "XAF" },
  { code: "SD", name: "Sudan", regionKey: "middle_east_africa", currencyCode: "SDG" },
  { code: "SS", name: "South Sudan", regionKey: "middle_east_africa", currencyCode: "SSP" },
  { code: "ER", name: "Eritrea", regionKey: "middle_east_africa", currencyCode: "ERN" },
  { code: "DJ", name: "Djibouti", regionKey: "middle_east_africa", currencyCode: "DJF" },
  { code: "SO", name: "Somalia", regionKey: "middle_east_africa", currencyCode: "SOS" },
  { code: "ET", name: "Ethiopia", regionKey: "middle_east_africa", currencyCode: "ETB" },
  { code: "KE", name: "Kenya", regionKey: "middle_east_africa", currencyCode: "KES" },
  { code: "UG", name: "Uganda", regionKey: "middle_east_africa", currencyCode: "UGX" },
  { code: "TZ", name: "Tanzania", regionKey: "middle_east_africa", currencyCode: "TZS" },
  { code: "RW", name: "Rwanda", regionKey: "middle_east_africa", currencyCode: "RWF" },
  { code: "BI", name: "Burundi", regionKey: "middle_east_africa", currencyCode: "BIF" },
  { code: "SC", name: "Seychelles", regionKey: "middle_east_africa", currencyCode: "SCR" },
  { code: "KM", name: "Comoros", regionKey: "middle_east_africa", currencyCode: "KMF" },
  { code: "MG", name: "Madagascar", regionKey: "middle_east_africa", currencyCode: "MGA" },
  { code: "MU", name: "Mauritius", regionKey: "middle_east_africa", currencyCode: "MUR" },
  { code: "MZ", name: "Mozambique", regionKey: "middle_east_africa", currencyCode: "MZN" },
  { code: "MW", name: "Malawi", regionKey: "middle_east_africa", currencyCode: "MWK" },
  { code: "ZM", name: "Zambia", regionKey: "middle_east_africa", currencyCode: "ZMW" },
  { code: "ZW", name: "Zimbabwe", regionKey: "middle_east_africa", currencyCode: "ZWL" },
  { code: "BW", name: "Botswana", regionKey: "middle_east_africa", currencyCode: "BWP" },
  { code: "NA", name: "Namibia", regionKey: "middle_east_africa", currencyCode: "NAD" },
  { code: "ZA", name: "South Africa", regionKey: "middle_east_africa", currencyCode: "ZAR" },
  { code: "LS", name: "Lesotho", regionKey: "middle_east_africa", currencyCode: "LSL" },
  { code: "SZ", name: "Eswatini", regionKey: "middle_east_africa", currencyCode: "SZL" },
  { code: "AO", name: "Angola", regionKey: "middle_east_africa", currencyCode: "AOA" },
  { code: "CD", name: "DR Congo", regionKey: "middle_east_africa", currencyCode: "CDF" },
  { code: "CG", name: "Congo Republic", regionKey: "middle_east_africa", currencyCode: "XAF" },
  { code: "CM", name: "Cameroon", regionKey: "middle_east_africa", currencyCode: "XAF" },
  {
    code: "CF",
    name: "Central African Republic",
    regionKey: "middle_east_africa",
    currencyCode: "XAF",
  },
  { code: "GQ", name: "Equatorial Guinea", regionKey: "middle_east_africa", currencyCode: "XAF" },
  { code: "GA", name: "Gabon", regionKey: "middle_east_africa", currencyCode: "XAF" },
  {
    code: "ST",
    name: "São Tomé and Príncipe",
    regionKey: "middle_east_africa",
    currencyCode: "STN",
  },
  { code: "NG", name: "Nigeria", regionKey: "middle_east_africa", currencyCode: "NGN" },
  { code: "GH", name: "Ghana", regionKey: "middle_east_africa", currencyCode: "GHS" },
  { code: "CI", name: "Côte d'Ivoire", regionKey: "middle_east_africa", currencyCode: "XOF" },
  { code: "SN", name: "Senegal", regionKey: "middle_east_africa", currencyCode: "XOF" },
  { code: "GM", name: "Gambia", regionKey: "middle_east_africa", currencyCode: "GMD" },
  { code: "GW", name: "Guinea-Bissau", regionKey: "middle_east_africa", currencyCode: "XOF" },
  { code: "GN", name: "Guinea", regionKey: "middle_east_africa", currencyCode: "GNF" },
  { code: "SL", name: "Sierra Leone", regionKey: "middle_east_africa", currencyCode: "SLE" },
  { code: "LR", name: "Liberia", regionKey: "middle_east_africa", currencyCode: "LRD" },
  { code: "TG", name: "Togo", regionKey: "middle_east_africa", currencyCode: "XOF" },
  { code: "BJ", name: "Benin", regionKey: "middle_east_africa", currencyCode: "XOF" },
  { code: "BF", name: "Burkina Faso", regionKey: "middle_east_africa", currencyCode: "XOF" },
  { code: "CV", name: "Cabo Verde", regionKey: "middle_east_africa", currencyCode: "CVE" },
  {
    code: "TF",
    name: "French Southern Territories",
    regionKey: "middle_east_africa",
    currencyCode: "EUR",
  },
  {
    code: "SH",
    name: "Saint Helena, Ascension and Tristan da Cunha",
    regionKey: "middle_east_africa",
    currencyCode: "SHP",
  },
  { code: "YT", name: "Mayotte", regionKey: "middle_east_africa", currencyCode: "EUR" },
  { code: "RE", name: "Réunion", regionKey: "middle_east_africa", currencyCode: "EUR" },

  // --- India ---
  { code: "IN", name: "India", regionKey: "india", currencyCode: "INR" },

  // --- Greater China ---
  { code: "CN", name: "China", regionKey: "greater_china", currencyCode: "CNY" },
  { code: "HK", name: "Hong Kong", regionKey: "greater_china", currencyCode: "HKD" },
  { code: "MO", name: "Macau", regionKey: "greater_china", currencyCode: "MOP" },
  { code: "TW", name: "Taiwan", regionKey: "greater_china", currencyCode: "TWD" },

  // --- Asia Pacific (rest) ---
  { code: "JP", name: "Japan", regionKey: "apac", currencyCode: "JPY" },
  { code: "KR", name: "South Korea", regionKey: "apac", currencyCode: "KRW" },
  { code: "KP", name: "North Korea", regionKey: "apac", currencyCode: "KPW" },
  { code: "MN", name: "Mongolia", regionKey: "apac", currencyCode: "MNT" },
  { code: "VN", name: "Vietnam", regionKey: "apac", currencyCode: "VND" },
  { code: "LA", name: "Laos", regionKey: "apac", currencyCode: "LAK" },
  { code: "KH", name: "Cambodia", regionKey: "apac", currencyCode: "KHR" },
  { code: "TH", name: "Thailand", regionKey: "apac", currencyCode: "THB" },
  { code: "MM", name: "Myanmar", regionKey: "apac", currencyCode: "MMK" },
  { code: "MY", name: "Malaysia", regionKey: "apac", currencyCode: "MYR" },
  { code: "SG", name: "Singapore", regionKey: "apac", currencyCode: "SGD" },
  { code: "ID", name: "Indonesia", regionKey: "apac", currencyCode: "IDR" },
  { code: "BN", name: "Brunei", regionKey: "apac", currencyCode: "BND" },
  { code: "PH", name: "Philippines", regionKey: "apac", currencyCode: "PHP" },
  { code: "TL", name: "Timor-Leste", regionKey: "apac", currencyCode: "USD" },
  { code: "PK", name: "Pakistan", regionKey: "apac", currencyCode: "PKR" },
  { code: "AF", name: "Afghanistan", regionKey: "apac", currencyCode: "AFN" },
  { code: "BD", name: "Bangladesh", regionKey: "apac", currencyCode: "BDT" },
  { code: "LK", name: "Sri Lanka", regionKey: "apac", currencyCode: "LKR" },
  { code: "NP", name: "Nepal", regionKey: "apac", currencyCode: "NPR" },
  { code: "BT", name: "Bhutan", regionKey: "apac", currencyCode: "BTN" },
  { code: "MV", name: "Maldives", regionKey: "apac", currencyCode: "MVR" },
  { code: "KZ", name: "Kazakhstan", regionKey: "apac", currencyCode: "KZT" },
  { code: "UZ", name: "Uzbekistan", regionKey: "apac", currencyCode: "UZS" },
  { code: "TM", name: "Turkmenistan", regionKey: "apac", currencyCode: "TMT" },
  { code: "TJ", name: "Tajikistan", regionKey: "apac", currencyCode: "TJS" },
  { code: "KG", name: "Kyrgyzstan", regionKey: "apac", currencyCode: "KGS" },
  { code: "AU", name: "Australia", regionKey: "apac", currencyCode: "AUD" },
  { code: "NZ", name: "New Zealand", regionKey: "apac", currencyCode: "NZD" },
  { code: "PG", name: "Papua New Guinea", regionKey: "apac", currencyCode: "PGK" },
  { code: "FJ", name: "Fiji", regionKey: "apac", currencyCode: "FJD" },
  { code: "SB", name: "Solomon Islands", regionKey: "apac", currencyCode: "SBD" },
  { code: "VU", name: "Vanuatu", regionKey: "apac", currencyCode: "VUV" },
  { code: "NC", name: "New Caledonia", regionKey: "apac", currencyCode: "XPF" },
  { code: "PF", name: "French Polynesia", regionKey: "apac", currencyCode: "XPF" },
  { code: "WS", name: "Samoa", regionKey: "apac", currencyCode: "WST" },
  { code: "TO", name: "Tonga", regionKey: "apac", currencyCode: "TOP" },
  { code: "KI", name: "Kiribati", regionKey: "apac", currencyCode: "AUD" },
  { code: "TV", name: "Tuvalu", regionKey: "apac", currencyCode: "AUD" },
  { code: "NR", name: "Nauru", regionKey: "apac", currencyCode: "AUD" },
  { code: "PW", name: "Palau", regionKey: "apac", currencyCode: "USD" },
  { code: "FM", name: "Micronesia", regionKey: "apac", currencyCode: "USD" },
  { code: "MH", name: "Marshall Islands", regionKey: "apac", currencyCode: "USD" },
  { code: "CK", name: "Cook Islands", regionKey: "apac", currencyCode: "NZD" },
  { code: "NU", name: "Niue", regionKey: "apac", currencyCode: "NZD" },
  { code: "TK", name: "Tokelau", regionKey: "apac", currencyCode: "NZD" },
  { code: "AS", name: "American Samoa", regionKey: "apac", currencyCode: "USD" },
  { code: "GU", name: "Guam", regionKey: "apac", currencyCode: "USD" },
  { code: "MP", name: "Northern Mariana Islands", regionKey: "apac", currencyCode: "USD" },
  { code: "IO", name: "British Indian Ocean Territory", regionKey: "apac", currencyCode: "USD" },
  { code: "CX", name: "Christmas Island", regionKey: "apac", currencyCode: "AUD" },
  { code: "CC", name: "Cocos (Keeling) Islands", regionKey: "apac", currencyCode: "AUD" },
  { code: "NF", name: "Norfolk Island", regionKey: "apac", currencyCode: "AUD" },
  { code: "HM", name: "Heard Island and McDonald Islands", regionKey: "apac", currencyCode: "AUD" },
  { code: "PN", name: "Pitcairn Islands", regionKey: "apac", currencyCode: "NZD" },
  {
    code: "UM",
    name: "United States Minor Outlying Islands",
    regionKey: "apac",
    currencyCode: "USD",
  },
  { code: "AQ", name: "Antarctica", regionKey: "apac", currencyCode: "USD" },
] as const;

export function findWorldCountry(code: string): WorldCountry | undefined {
  const normalized = code.trim().toUpperCase();
  return WORLD_COUNTRIES.find((country) => country.code === normalized);
}

export const WORLD_CURRENCY_CODES: readonly string[] = Array.from(
  new Set(WORLD_COUNTRIES.map((country) => country.currencyCode)),
).sort();
