/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDealDocumentsRouteImport } from './routes/_authenticated/deal-documents'
import { Route as AuthenticatedDealsRouteImport } from './routes/_authenticated/deals'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedPartnerRouteImport } from './routes/_authenticated/partner'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedRewardsRouteImport } from './routes/_authenticated/rewards'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminCatalogRouteImport } from './routes/_authenticated/admin.catalog'
import { Route as AuthenticatedAdminDealsRouteImport } from './routes/_authenticated/admin.deals'
import { Route as AuthenticatedAdminNewsRouteImport } from './routes/_authenticated/admin.news'
import { Route as AuthenticatedAdminPartnersRouteImport } from './routes/_authenticated/admin.partners'
import { Route as AuthenticatedAdminRewardsRouteImport } from './routes/_authenticated/admin.rewards'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedPartnerAgreementRouteImport } from './routes/_authenticated/partner.agreement'
import { Route as AuthenticatedPartnerOnboardingRouteImport } from './routes/_authenticated/partner.onboarding'
import { Route as AuthenticatedPartnerTeamRouteImport } from './routes/_authenticated/partner.team'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDealDocumentsRoute =
  AuthenticatedDealDocumentsRouteImport.update({
    id: '/deal-documents',
    path: '/deal-documents',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDealsRoute = AuthenticatedDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPartnerRoute = AuthenticatedPartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRewardsRoute = AuthenticatedRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminCatalogRoute =
  AuthenticatedAdminCatalogRouteImport.update({
    id: '/admin/catalog',
    path: '/admin/catalog',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDealsRoute = AuthenticatedAdminDealsRouteImport.update({
  id: '/admin/deals',
  path: '/admin/deals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminNewsRoute = AuthenticatedAdminNewsRouteImport.update({
  id: '/admin/news',
  path: '/admin/news',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminPartnersRoute =
  AuthenticatedAdminPartnersRouteImport.update({
    id: '/admin/partners',
    path: '/admin/partners',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRewardsRoute =
  AuthenticatedAdminRewardsRouteImport.update({
    id: '/admin/rewards',
    path: '/admin/rewards',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPartnerAgreementRoute =
  AuthenticatedPartnerAgreementRouteImport.update({
    id: '/agreement',
    path: '/agreement',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedPartnerOnboardingRoute =
  AuthenticatedPartnerOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedPartnerTeamRoute =
  AuthenticatedPartnerTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deal-documents': typeof AuthenticatedDealDocumentsRoute
  '/deals': typeof AuthenticatedDealsRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/partner': typeof AuthenticatedPartnerRouteWithChildren
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/rewards': typeof AuthenticatedRewardsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/admin/deals': typeof AuthenticatedAdminDealsRoute
  '/admin/news': typeof AuthenticatedAdminNewsRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/rewards': typeof AuthenticatedAdminRewardsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/partner/agreement': typeof AuthenticatedPartnerAgreementRoute
  '/partner/onboarding': typeof AuthenticatedPartnerOnboardingRoute
  '/partner/team': typeof AuthenticatedPartnerTeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deal-documents': typeof AuthenticatedDealDocumentsRoute
  '/deals': typeof AuthenticatedDealsRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/partner': typeof AuthenticatedPartnerRouteWithChildren
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/rewards': typeof AuthenticatedRewardsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/admin/deals': typeof AuthenticatedAdminDealsRoute
  '/admin/news': typeof AuthenticatedAdminNewsRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/rewards': typeof AuthenticatedAdminRewardsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/partner/agreement': typeof AuthenticatedPartnerAgreementRoute
  '/partner/onboarding': typeof AuthenticatedPartnerOnboardingRoute
  '/partner/team': typeof AuthenticatedPartnerTeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deal-documents': typeof AuthenticatedDealDocumentsRoute
  '/_authenticated/deals': typeof AuthenticatedDealsRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/partner': typeof AuthenticatedPartnerRouteWithChildren
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/rewards': typeof AuthenticatedRewardsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/_authenticated/admin/deals': typeof AuthenticatedAdminDealsRoute
  '/_authenticated/admin/news': typeof AuthenticatedAdminNewsRoute
  '/_authenticated/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/_authenticated/admin/rewards': typeof AuthenticatedAdminRewardsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/partner/agreement': typeof AuthenticatedPartnerAgreementRoute
  '/_authenticated/partner/onboarding': typeof AuthenticatedPartnerOnboardingRoute
  '/_authenticated/partner/team': typeof AuthenticatedPartnerTeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/analytics'
    | '/customers'
    | '/dashboard'
    | '/deal-documents'
    | '/deals'
    | '/documents'
    | '/notifications'
    | '/partner'
    | '/pipeline'
    | '/rewards'
    | '/settings'
    | '/support'
    | '/admin/audit'
    | '/admin/catalog'
    | '/admin/deals'
    | '/admin/news'
    | '/admin/partners'
    | '/admin/rewards'
    | '/admin/users'
    | '/partner/agreement'
    | '/partner/onboarding'
    | '/partner/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/analytics'
    | '/customers'
    | '/dashboard'
    | '/deal-documents'
    | '/deals'
    | '/documents'
    | '/notifications'
    | '/partner'
    | '/pipeline'
    | '/rewards'
    | '/settings'
    | '/support'
    | '/admin/audit'
    | '/admin/catalog'
    | '/admin/deals'
    | '/admin/news'
    | '/admin/partners'
    | '/admin/rewards'
    | '/admin/users'
    | '/partner/agreement'
    | '/partner/onboarding'
    | '/partner/team'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/analytics'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/deal-documents'
    | '/_authenticated/deals'
    | '/_authenticated/documents'
    | '/_authenticated/notifications'
    | '/_authenticated/partner'
    | '/_authenticated/pipeline'
    | '/_authenticated/rewards'
    | '/_authenticated/settings'
    | '/_authenticated/support'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/catalog'
    | '/_authenticated/admin/deals'
    | '/_authenticated/admin/news'
    | '/_authenticated/admin/partners'
    | '/_authenticated/admin/rewards'
    | '/_authenticated/admin/users'
    | '/_authenticated/partner/agreement'
    | '/_authenticated/partner/onboarding'
    | '/_authenticated/partner/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deal-documents': {
      id: '/_authenticated/deal-documents'
      path: '/deal-documents'
      fullPath: '/deal-documents'
      preLoaderRoute: typeof AuthenticatedDealDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deals': {
      id: '/_authenticated/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof AuthenticatedDealsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/partner': {
      id: '/_authenticated/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof AuthenticatedPartnerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rewards': {
      id: '/_authenticated/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof AuthenticatedRewardsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/catalog': {
      id: '/_authenticated/admin/catalog'
      path: '/admin/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AuthenticatedAdminCatalogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/deals': {
      id: '/_authenticated/admin/deals'
      path: '/admin/deals'
      fullPath: '/admin/deals'
      preLoaderRoute: typeof AuthenticatedAdminDealsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/news': {
      id: '/_authenticated/admin/news'
      path: '/admin/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AuthenticatedAdminNewsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/partners': {
      id: '/_authenticated/admin/partners'
      path: '/admin/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AuthenticatedAdminPartnersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/rewards': {
      id: '/_authenticated/admin/rewards'
      path: '/admin/rewards'
      fullPath: '/admin/rewards'
      preLoaderRoute: typeof AuthenticatedAdminRewardsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/partner/agreement': {
      id: '/_authenticated/partner/agreement'
      path: '/agreement'
      fullPath: '/partner/agreement'
      preLoaderRoute: typeof AuthenticatedPartnerAgreementRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/partner/onboarding': {
      id: '/_authenticated/partner/onboarding'
      path: '/onboarding'
      fullPath: '/partner/onboarding'
      preLoaderRoute: typeof AuthenticatedPartnerOnboardingRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/partner/team': {
      id: '/_authenticated/partner/team'
      path: '/team'
      fullPath: '/partner/team'
      preLoaderRoute: typeof AuthenticatedPartnerTeamRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
  }
}

interface AuthenticatedPartnerRouteChildren {
  AuthenticatedPartnerAgreementRoute: typeof AuthenticatedPartnerAgreementRoute
  AuthenticatedPartnerOnboardingRoute: typeof AuthenticatedPartnerOnboardingRoute
  AuthenticatedPartnerTeamRoute: typeof AuthenticatedPartnerTeamRoute
}

const AuthenticatedPartnerRouteChildren: AuthenticatedPartnerRouteChildren = {
  AuthenticatedPartnerAgreementRoute: AuthenticatedPartnerAgreementRoute,
  AuthenticatedPartnerOnboardingRoute: AuthenticatedPartnerOnboardingRoute,
  AuthenticatedPartnerTeamRoute: AuthenticatedPartnerTeamRoute,
}

const AuthenticatedPartnerRouteWithChildren =
  AuthenticatedPartnerRoute._addFileChildren(AuthenticatedPartnerRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDealDocumentsRoute: typeof AuthenticatedDealDocumentsRoute
  AuthenticatedDealsRoute: typeof AuthenticatedDealsRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPartnerRoute: typeof AuthenticatedPartnerRouteWithChildren
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedRewardsRoute: typeof AuthenticatedRewardsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminCatalogRoute: typeof AuthenticatedAdminCatalogRoute
  AuthenticatedAdminDealsRoute: typeof AuthenticatedAdminDealsRoute
  AuthenticatedAdminNewsRoute: typeof AuthenticatedAdminNewsRoute
  AuthenticatedAdminPartnersRoute: typeof AuthenticatedAdminPartnersRoute
  AuthenticatedAdminRewardsRoute: typeof AuthenticatedAdminRewardsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDealDocumentsRoute: AuthenticatedDealDocumentsRoute,
  AuthenticatedDealsRoute: AuthenticatedDealsRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPartnerRoute: AuthenticatedPartnerRouteWithChildren,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedRewardsRoute: AuthenticatedRewardsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminCatalogRoute: AuthenticatedAdminCatalogRoute,
  AuthenticatedAdminDealsRoute: AuthenticatedAdminDealsRoute,
  AuthenticatedAdminNewsRoute: AuthenticatedAdminNewsRoute,
  AuthenticatedAdminPartnersRoute: AuthenticatedAdminPartnersRoute,
  AuthenticatedAdminRewardsRoute: AuthenticatedAdminRewardsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
