ALTER TABLE portal_deals
  ADD COLUMN IF NOT EXISTS currency_code TEXT NOT NULL DEFAULT 'INR',
  ADD COLUMN IF NOT EXISTS amount_value NUMERIC(14,2),
  ADD COLUMN IF NOT EXISTS amount_inr NUMERIC(14,2),
  ADD COLUMN IF NOT EXISTS fx_rate NUMERIC(14,6),
  ADD COLUMN IF NOT EXISTS fx_provider TEXT,
  ADD COLUMN IF NOT EXISTS fx_rate_fetched_at TIMESTAMPTZ;
